"""Transcript-equivalence harness between the Rust (`catanatron_rs`) engine and the
vendored Python reference engine (`vendor/catanatron`).

The two engines have independent RNGs (Rust: `rand`/`SmallRng`; Python: CPython's
Mersenne Twister), so passing the "same" integer seed to both does **not** produce
the same map, seating order, dice rolls, robber steals, or development-card draws.
This module works around that by:

1. Using the fixed, non-shuffled `TOURNAMENT` map on both sides (verified bit-for-bit
   identical: same tile coordinate -> (resource, number) and same node/edge ids).
2. Building the Rust game first, reading its *actual* post-shuffle seating order off
   its snapshot, then constructing the Python game with players pre-ordered to match
   (bypassing Python's internal `random.sample` seating shuffle via a monkeypatch).
3. Treating ROLL, MOVE_ROBBER-with-victim, and BUY_DEVELOPMENT_CARD as explicit
   chance nodes: sampling an outcome ourselves, applying it to the Rust engine via
   `apply_chance_outcome`, identifying the concrete effect from the outcome's
   snapshot diff, and forcing that exact effect into the Python engine via
   `ActionRecord.result` (dice pair / stolen resource / drawn card). Python's
   `draw_from_listdeck` matches cards by value regardless of deck order, so the two
   engines' independently-shuffled development-card decks never need to agree on
   order -- only on remaining counts per card type, which stay in sync because we
   always force the same card.

Pre-fix Rust wheels (< 0.1.2) had two chance-spectrum bugs this harness had to
work around, both now fixed upstream (verify with `catanatron_rs` version):
MOVE_ROBBER-with-victim used to return 5 outcomes in fixed resource order
``[WOOD, BRICK, SHEEP, WHEAT, ORE]`` at uniform 0.2 probability regardless of
the victim's actual hand (applying an outcome for a resource the victim
didn't hold was a silent no-op with no Python equivalent), and
BUY_DEVELOPMENT_CARD could return a "phantom" outcome that drew no card at
all. `apply_chance_step` handles both action types the same way regardless of
which wheel is in front of it: materialize every spectrum outcome, diff it
against the pre-state to classify it as a real single-resource-steal/card-draw
or a phantom no-op, and sample (renormalized) only among the real ones. Against
a fixed wheel every outcome is real, so this reduces to trusting the engine's
own (now-correct) probabilities; against a pre-fix wheel it filters out the
impossible ones. `ChanceOutcome.detail["phantom_outcomes"]` reports how many
(if any) were filtered, so a fixed wheel should show zero.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Iterable, Sequence
from unittest.mock import patch

from catan_zero.rl._catanatron import import_catanatron_module

RESOURCES: tuple[str, ...] = ("WOOD", "BRICK", "SHEEP", "WHEAT", "ORE")
DEVELOPMENT_CARDS: tuple[str, ...] = (
    "KNIGHT",
    "YEAR_OF_PLENTY",
    "MONOPOLY",
    "ROAD_BUILDING",
    "VICTORY_POINT",
)

# Action types generated by both engines that carry no `.value` payload.
_NO_VALUE_ACTION_TYPES = frozenset(
    {"ROLL", "END_TURN", "BUY_DEVELOPMENT_CARD", "PLAY_KNIGHT_CARD", "PLAY_ROAD_BUILDING"}
)


class ActionMappingGap(RuntimeError):
    """Raised when a Rust action cannot be faithfully translated to a Python Action."""


class RustModuleUnavailable(RuntimeError):
    """Raised when `catanatron_rs` cannot be imported."""


def require_rust_module() -> Any:
    try:
        import catanatron_rs  # type: ignore
    except ImportError as error:  # pragma: no cover - exercised only without the wheel.
        raise RustModuleUnavailable(
            "catanatron_rs is required for the equivalence harness."
        ) from error
    required = (
        "Game",
        "playable_action_indices",
    )
    game = catanatron_rs.Game.simple(["RED", "BLUE"], seed=0)
    missing = [name for name in ("playable_action_indices", "playable_actions_json", "execute_action_index", "spectrum_json", "apply_chance_outcome", "json_snapshot", "winning_color", "copy", "current_color", "set_player_hand") if not hasattr(game, name)]
    if missing:
        raise RustModuleUnavailable(
            "installed catanatron_rs is missing required bindings: " + ", ".join(missing)
        )
    return catanatron_rs


@dataclass(frozen=True, slots=True)
class VendorSymbols:
    Color: Any
    Player: Any
    Action: Any
    ActionType: Any
    ActionRecord: Any
    ActionPrompt: Any
    State: Any
    PyGame: Any
    build_map: Any
    player_key: Any


_SYMBOLS_CACHE: VendorSymbols | None = None


def vendor_symbols() -> VendorSymbols:
    global _SYMBOLS_CACHE
    if _SYMBOLS_CACHE is not None:
        return _SYMBOLS_CACHE
    player_module = import_catanatron_module("catanatron.models.player")
    enums_module = import_catanatron_module("catanatron.models.enums")
    map_module = import_catanatron_module("catanatron.models.map")
    state_module = import_catanatron_module("catanatron.state")
    game_module = import_catanatron_module("catanatron.game")
    state_functions_module = import_catanatron_module("catanatron.state_functions")
    _SYMBOLS_CACHE = VendorSymbols(
        Color=player_module.Color,
        Player=player_module.Player,
        Action=enums_module.Action,
        ActionType=enums_module.ActionType,
        ActionRecord=enums_module.ActionRecord,
        ActionPrompt=enums_module.ActionPrompt,
        State=state_module.State,
        PyGame=game_module.Game,
        build_map=map_module.build_map,
        player_key=state_functions_module.player_key,
    )
    return _SYMBOLS_CACHE


@dataclass(frozen=True, slots=True)
class EquivalenceConfig:
    colors: tuple[str, ...] = ("RED", "BLUE")
    map_kind: str = "TOURNAMENT"
    vps_to_win: int = 10
    discard_limit: int = 7
    friendly_robber: bool = False
    max_steps: int = 2000


def _canon(value: Any) -> Any:
    """Canonicalize a JSON-ish or enum-ish value for cross-engine comparison."""
    if value is None:
        return None
    if isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, (list, tuple)):
        return tuple(_canon(item) for item in value)
    name = getattr(value, "name", None)
    if name is not None:
        return _canon(str(name))
    return value


def canonical_rust_action_key(raw: Sequence[Any]) -> tuple[str, str, Any]:
    color, action_type, value = raw[0], raw[1], raw[2]
    return (str(color), str(action_type), _canonical_value_for_type(str(action_type), value))


def canonical_python_action_key(action: Any) -> tuple[str, str, Any]:
    action_type = action.action_type.name
    return (str(action.color.name), action_type, _canonical_value_for_type(action_type, action.value))


def _canonical_value_for_type(action_type: str, value: Any) -> Any:
    if action_type in _NO_VALUE_ACTION_TYPES:
        return None
    if action_type == "BUILD_ROAD":
        edge = tuple(int(node) for node in value)
        return tuple(sorted(edge))
    if action_type == "MOVE_ROBBER":
        coordinate = tuple(int(c) for c in value[0])
        victim = value[1]
        victim_key = str(getattr(victim, "name", victim)) if victim is not None else None
        return (coordinate, victim_key)
    if action_type == "PLAY_YEAR_OF_PLENTY":
        cards = tuple(str(getattr(card, "name", card)) for card in value)
        return tuple(sorted(cards, key=RESOURCES.index))
    return _canon(value)


def raw_action_to_python_action(raw: Sequence[Any], symbols: VendorSymbols) -> Any:
    color_name, action_type_name, value = raw[0], raw[1], raw[2]
    try:
        color = getattr(symbols.Color, str(color_name))
        action_type = getattr(symbols.ActionType, str(action_type_name))
    except AttributeError as error:
        raise ActionMappingGap(f"unknown color/action_type in raw action {raw!r}") from error

    if action_type_name in _NO_VALUE_ACTION_TYPES:
        return symbols.Action(color, action_type, None)
    if action_type_name in ("BUILD_SETTLEMENT", "BUILD_CITY"):
        return symbols.Action(color, action_type, int(value))
    if action_type_name == "BUILD_ROAD":
        edge = tuple(int(node) for node in value)
        return symbols.Action(color, action_type, edge)
    if action_type_name in ("DISCARD_RESOURCE", "PLAY_MONOPOLY"):
        return symbols.Action(color, action_type, str(value))
    if action_type_name == "MOVE_ROBBER":
        coordinate = tuple(int(c) for c in value[0])
        victim_name = value[1]
        victim = getattr(symbols.Color, str(victim_name)) if victim_name is not None else None
        return symbols.Action(color, action_type, (coordinate, victim))
    if action_type_name == "MARITIME_TRADE":
        converted = tuple(str(item) if item is not None else None for item in value)
        return symbols.Action(color, action_type, converted)
    if action_type_name == "PLAY_YEAR_OF_PLENTY":
        cards = tuple(str(card) for card in value)
        cards = tuple(sorted(cards, key=RESOURCES.index))
        return symbols.Action(color, action_type, cards)
    raise ActionMappingGap(
        f"no Python mapping implemented for Rust action_type={action_type_name!r} raw={raw!r}"
    )


def build_paired_games(seed: int, config: EquivalenceConfig) -> tuple[Any, Any, tuple[str, ...]]:
    """Construct a Rust game and a seating-aligned Python game for the same setup.

    The Rust engine's own (uncontrollable) seating shuffle is treated as ground
    truth; the Python engine's seating shuffle is bypassed to match it exactly.
    """
    catanatron_rs = require_rust_module()
    rust_game = catanatron_rs.Game(
        colors=list(config.colors),
        seed=seed,
        map_kind=config.map_kind,
        vps_to_win=config.vps_to_win,
        discard_limit=config.discard_limit,
        friendly_robber=config.friendly_robber,
    )
    snapshot = json.loads(rust_game.json_snapshot())
    seated_colors = tuple(str(color) for color in snapshot["colors"])

    symbols = vendor_symbols()
    catan_map = symbols.build_map(config.map_kind)
    players = [symbols.Player(getattr(symbols.Color, name)) for name in seated_colors]

    with patch("catanatron.state.random.sample", lambda seq, _k: list(seq)):
        python_game = symbols.PyGame(
            players=players,
            seed=seed,
            discard_limit=config.discard_limit,
            friendly_robber=config.friendly_robber,
            vps_to_win=config.vps_to_win,
            catan_map=catan_map,
        )
    return rust_game, python_game, seated_colors


def rust_legal_actions(rust_game: Any, seated_colors: Sequence[str], map_kind: str) -> tuple[list[int], list[Any]]:
    ids = [int(i) for i in rust_game.playable_action_indices(list(seated_colors), map_kind)]
    raw = json.loads(rust_game.playable_actions_json())
    if len(ids) != len(raw):
        raise RuntimeError(f"rust action id/json length mismatch: {len(ids)} vs {len(raw)}")
    return ids, raw


def legal_action_diff(
    rust_raw_actions: Iterable[Sequence[Any]], python_actions: Iterable[Any]
) -> tuple[set[tuple[str, str, Any]], set[tuple[str, str, Any]]]:
    rust_keys = {canonical_rust_action_key(raw) for raw in rust_raw_actions}
    python_keys = {canonical_python_action_key(action) for action in python_actions}
    return rust_keys - python_keys, python_keys - rust_keys


def rust_state_view(rust_game: Any) -> dict[str, Any]:
    snapshot = json.loads(rust_game.json_snapshot())
    colors = [str(color) for color in snapshot["colors"]]
    players = []
    for ps in snapshot["player_state"]:
        players.append(
            {
                "victory_points": int(ps["victory_points"]),
                "actual_victory_points": int(ps["actual_victory_points"]),
                "resources": {r: int(ps["resources"][r]) for r in RESOURCES},
                "dev_cards": {d: int(ps["dev_cards"][d]) for d in DEVELOPMENT_CARDS},
                "longest_road_length": int(ps["longest_road_length"]),
                "roads_available": int(ps["roads_available"]),
                "settlements_available": int(ps["settlements_available"]),
                "cities_available": int(ps["cities_available"]),
                "has_army": bool(ps["has_army"]),
                "played_dev_cards": {d: int(ps["played_dev_cards"][d]) for d in DEVELOPMENT_CARDS},
            }
        )
    buildings = {
        int(node["id"]): (str(node["color"]), str(node["building"]))
        for node in snapshot["nodes"].values()
        if node.get("building") is not None
    }
    roads = {}
    for edge in snapshot["edges"]:
        if edge.get("color") is not None:
            key = tuple(sorted(int(n) for n in edge["id"]))
            roads[key] = str(edge["color"])
    winner = snapshot.get("winning_color")
    return {
        "colors": colors,
        "current_color": colors[int(snapshot["current_player_index"])],
        "players": players,
        "resource_bank": {r: int(snapshot["resource_bank"][r]) for r in RESOURCES},
        "robber_coordinate": tuple(int(c) for c in snapshot["robber_coordinate"]),
        "buildings": buildings,
        "roads": roads,
        "winner": str(winner) if winner is not None else None,
        "development_deck_count": int(snapshot["development_deck_count"]),
        "is_road_building": bool(snapshot["is_road_building"]),
        "free_roads_available": int(snapshot["free_roads_available"]),
    }


def python_state_view(python_game: Any, symbols: VendorSymbols) -> dict[str, Any]:
    state = python_game.state
    colors = [color.name for color in state.colors]
    players = []
    for color in state.colors:
        key = symbols.player_key(state, color)
        players.append(
            {
                "victory_points": int(state.player_state[f"{key}_VICTORY_POINTS"]),
                "actual_victory_points": int(state.player_state[f"{key}_ACTUAL_VICTORY_POINTS"]),
                "resources": {r: int(state.player_state[f"{key}_{r}_IN_HAND"]) for r in RESOURCES},
                "dev_cards": {d: int(state.player_state[f"{key}_{d}_IN_HAND"]) for d in DEVELOPMENT_CARDS},
                "longest_road_length": int(state.player_state[f"{key}_LONGEST_ROAD_LENGTH"]),
                "roads_available": int(state.player_state[f"{key}_ROADS_AVAILABLE"]),
                "settlements_available": int(state.player_state[f"{key}_SETTLEMENTS_AVAILABLE"]),
                "cities_available": int(state.player_state[f"{key}_CITIES_AVAILABLE"]),
                "has_army": bool(state.player_state[f"{key}_HAS_ARMY"]),
                "played_dev_cards": {
                    d: int(state.player_state[f"{key}_PLAYED_{d}"]) for d in DEVELOPMENT_CARDS
                },
            }
        )
    buildings = {
        int(node_id): (color.name, str(building_type))
        for node_id, (color, building_type) in state.board.buildings.items()
    }
    roads = {}
    for edge, color in state.board.roads.items():
        key = tuple(sorted(int(n) for n in edge))
        roads[key] = color.name
    winner = python_game.winning_color()
    resource_bank = dict(zip(RESOURCES, (int(v) for v in state.resource_freqdeck)))
    return {
        "colors": colors,
        "current_color": state.current_color().name,
        "players": players,
        "resource_bank": resource_bank,
        "robber_coordinate": tuple(int(c) for c in state.board.robber_coordinate),
        "buildings": buildings,
        "roads": roads,
        "winner": winner.name if winner is not None else None,
        "development_deck_count": len(state.development_listdeck),
        "is_road_building": bool(state.is_road_building),
        "free_roads_available": int(state.free_roads_available),
    }


def diff_state_views(rust_view: dict[str, Any], python_view: dict[str, Any]) -> list[str]:
    mismatches: list[str] = []
    for key in (
        "current_color",
        "robber_coordinate",
        "winner",
        "resource_bank",
        "buildings",
        "roads",
        "development_deck_count",
        "is_road_building",
        "free_roads_available",
    ):
        if rust_view.get(key) != python_view.get(key):
            mismatches.append(f"{key}: rust={rust_view.get(key)!r} python={python_view.get(key)!r}")
    if len(rust_view["players"]) != len(python_view["players"]):
        mismatches.append(
            f"players length: rust={len(rust_view['players'])} python={len(python_view['players'])}"
        )
    else:
        for index, (rp, pp) in enumerate(zip(rust_view["players"], python_view["players"])):
            if rp != pp:
                mismatches.append(f"players[{index}]: rust={rp!r} python={pp!r}")
    return mismatches


# Verified, pre-existing bugs in the vendored Python engine's longest-road logic
# (rules audit 2026-07-02): sub-5 settlement-cut never revokes Longest Road,
# both-ends-enemy-capped roads undercount length by 1 (matches upstream #378),
# and roads may be buildable through enemy settlements (matches upstream #376).
# Because of this, any divergence touching longest-road length/ownership, or
# BUILD_ROAD legality near an enemy-occupied node, must NOT be auto-attributed
# to "Rust is wrong" or "Python is wrong" -- either engine could be the buggy
# one (or both, differently). `classify_divergence_topic` buckets these into
# "rules_adjudication_needed" instead of asserting a verdict; only fixer-side
# rules review (not this harness) can adjudicate them. Everything else (dice,
# resources, dev cards, robber, bank, current player, win detection) is
# unaffected by that audit and is treated as ground-truth-comparable as before.
def classify_state_divergence_topic(
    rust_view: dict[str, Any], python_view: dict[str, Any], mismatches: list[str]
) -> str:
    """Bucket a state divergence into the longest-road adjudication topic only
    with *positive* evidence that longest-road bonus attribution -- not some
    other VP-granting mechanism -- is the cause. That means either:

    (a) `longest_road_length` itself differs between engines for the
        mismatched player, or
    (b) `longest_road_length` agrees (both engines see the same tied length)
        AND `has_army`/`played_dev_cards` (which would reveal a largest-army
        miscount) are identical, so largest army is positively ruled out as
        the VP source, with every other tracked field (resources, dev cards
        in hand, build-piece availability) also matching.

    A VP-only mismatch that can't be pinned on longest-road this way (e.g. a
    largest-army miscount, or any other novel bug) falls through to
    "unclassified", which is what should draw attention.
    """
    if not mismatches:
        return "none"
    non_player_mismatch = any(not entry.startswith("players[") for entry in mismatches)
    if non_player_mismatch:
        return "unclassified"

    for rp, pp in zip(rust_view["players"], python_view["players"]):
        if rp == pp:
            continue
        same_resources = rp["resources"] == pp["resources"]
        same_dev_cards = rp["dev_cards"] == pp["dev_cards"]
        same_availability = (
            rp["roads_available"] == pp["roads_available"]
            and rp["settlements_available"] == pp["settlements_available"]
            and rp["cities_available"] == pp["cities_available"]
        )
        # Rules out largest-army as the VP source (has_army flag + knight play
        # counts both agree between engines).
        same_army_evidence = (
            rp["has_army"] == pp["has_army"] and rp["played_dev_cards"] == pp["played_dev_cards"]
        )
        # By elimination: with resources, dev cards, build-piece availability,
        # and largest-army evidence all ruled out as the cause, any remaining
        # difference here must be victory_points/actual_victory_points and/or
        # longest_road_length itself -- i.e. concretely a longest-road-bonus
        # attribution or length disagreement, not some other novel mechanism.
        if not (same_resources and same_dev_cards and same_availability and same_army_evidence):
            return "unclassified"
    return "rules_adjudication_needed_longest_road"


def classify_legal_action_mismatch_topic(
    only_rust: set[tuple[str, str, Any]],
    only_python: set[tuple[str, str, Any]],
    buildings: dict[int, tuple[str, str]],
) -> str:
    """Bucket a legal-action mismatch into the buildable-edge adjudication
    topic only when every mismatched action is a BUILD_ROAD whose edge is
    actually adjacent to a node occupied by a *different* color than the
    acting player -- i.e. there's concrete board evidence of the
    through-enemy-node scenario, not just "some BUILD_ROAD disagreement"
    (which could be a different, novel bug).
    """
    mismatched = only_rust | only_python
    action_types = {key[1] for key in mismatched}
    if not action_types or action_types - {"BUILD_ROAD"}:
        return "unclassified"

    for color, _action_type, edge in mismatched:
        if not isinstance(edge, tuple) or len(edge) != 2:
            return "unclassified"
        adjacent_to_enemy_node = any(
            buildings.get(int(node)) is not None and buildings[int(node)][0] != str(color)
            for node in edge
        )
        if not adjacent_to_enemy_node:
            return "unclassified"
    return "rules_adjudication_needed_buildable_edge_near_enemy"


@dataclass(slots=True)
class ChanceOutcome:
    action_type: str
    detail: dict[str, Any]


def apply_chance_step(
    rust_game: Any,
    python_game: Any,
    raw_action: Sequence[Any],
    *,
    symbols: VendorSymbols,
    harness_rng: Any,
) -> tuple[Any, ChanceOutcome]:
    """Apply a chance action to both engines with the same forced outcome.

    Returns the (possibly new) rust_game object and a record of what happened.
    Mutates python_game in place (matching Game.execute's own mutation model).
    """
    action_type = str(raw_action[1])
    raw_json = json.dumps(raw_action)
    spectrum = json.loads(rust_game.spectrum_json(raw_json))

    if action_type == "ROLL":
        probabilities = [float(entry["probability"]) for entry in spectrum]
        outcome_index = _weighted_choice(harness_rng, probabilities)
        total = outcome_index + 2
        die_a = min(6, max(1, total - 1))
        die_b = total - die_a
        new_rust_game = rust_game.apply_chance_outcome(raw_json, outcome_index)

        py_action = raw_action_to_python_action(raw_action, symbols)
        python_game.execute(
            py_action,
            action_record=symbols.ActionRecord(action=py_action, result=(die_a, die_b)),
        )
        return new_rust_game, ChanceOutcome(action_type, {"total": total, "dice": (die_a, die_b)})

    if action_type == "MOVE_ROBBER":
        # NOTE: on the pre-fix Rust wheel, MOVE_ROBBER-with-victim spectra were
        # 5 fixed, uniformly-weighted outcomes in RESOURCES order regardless of
        # the victim's actual hand, and applying an outcome for a resource the
        # victim didn't hold was a silent no-op (no Python equivalent -- see
        # `test_move_robber_spectrum_is_uniform_not_hand_weighted`). The fixed
        # wheel (0.1.2+) instead returns exactly the hand-weighted outcomes
        # that can really happen. We handle both generically -- the same
        # materialize-every-outcome-and-diff pattern as BUY_DEVELOPMENT_CARD
        # below -- rather than assuming a fixed spectrum length or an
        # index<->resource mapping, so this keeps working whichever wheel is
        # in front of it and self-detects if either engine's semantics ever
        # change again.
        coordinate, victim_name = raw_action[2][0], raw_action[2][1]
        if victim_name is None:
            # Deterministic: no chance node. Caller should not have routed here.
            raise RuntimeError("MOVE_ROBBER without a victim is not a chance action")
        before = json.loads(rust_game.json_snapshot())
        colors = [str(color) for color in before["colors"]]
        victim_index = colors.index(str(victim_name))
        victim_hand_before = before["player_state"][victim_index]["resources"]
        if sum(int(v) for v in victim_hand_before.values()) <= 0:
            raise RuntimeError(
                f"MOVE_ROBBER victim {victim_name} has no cards to steal; this should be "
                "unreachable since Rust only offers a victim option when they hold >=1 card"
            )

        real_outcomes: list[tuple[int, float, str]] = []
        phantom_outcomes: list[int] = []
        materialized: dict[int, Any] = {}
        for outcome_index, entry in enumerate(spectrum):
            candidate_game = rust_game.apply_chance_outcome(raw_json, outcome_index)
            candidate_snapshot = json.loads(candidate_game.json_snapshot())
            candidate_hand = candidate_snapshot["player_state"][victim_index]["resources"]
            delta = {r: int(candidate_hand[r]) - int(victim_hand_before[r]) for r in RESOURCES}
            stolen = [r for r, d in delta.items() if d == -1]
            clean_single_steal = len(stolen) == 1 and all(d in (0, -1) for d in delta.values())
            if clean_single_steal:
                real_outcomes.append((outcome_index, float(entry["probability"]), stolen[0]))
                materialized[outcome_index] = candidate_game
            else:
                phantom_outcomes.append(outcome_index)

        if not real_outcomes:
            raise RuntimeError(
                f"MOVE_ROBBER spectrum has no real (single-resource-steal) outcomes: "
                f"spectrum={spectrum!r} victim_hand={victim_hand_before!r}"
            )

        weights = [prob for _, prob, _ in real_outcomes]
        selection = _weighted_choice(harness_rng, weights)
        outcome_index, _prob, resource = real_outcomes[selection]
        new_rust_game = materialized[outcome_index]

        py_action = raw_action_to_python_action(raw_action, symbols)
        python_game.execute(
            py_action,
            action_record=symbols.ActionRecord(action=py_action, result=resource),
        )
        return new_rust_game, ChanceOutcome(
            action_type,
            {"resource": resource, "victim": str(victim_name), "phantom_outcomes": phantom_outcomes},
        )

    if action_type == "BUY_DEVELOPMENT_CARD":
        # NOTE: Rust's BUY_DEVELOPMENT_CARD spectrum can include a "phantom"
        # outcome with substantial nonzero probability that draws no card at
        # all (deck count and actor's dev_cards unchanged). This has no
        # equivalent in Python, where buying always succeeds and draws a real
        # card whenever the deck is non-empty. We materialize every outcome
        # up front, discard the phantom ones, and resample (renormalized)
        # among only the real card-drawing outcomes -- see
        # ``phantom_outcomes`` in the returned detail for how often this
        # happens.
        actor_color = str(raw_action[0])
        before = json.loads(rust_game.json_snapshot())
        colors = [str(color) for color in before["colors"]]
        actor_index = colors.index(actor_color)
        before_cards = before["player_state"][actor_index]["dev_cards"]
        before_deck_count = int(before["development_deck_count"])

        real_outcomes: list[tuple[int, float, str]] = []
        phantom_outcomes: list[int] = []
        materialized: dict[int, Any] = {}
        for outcome_index, entry in enumerate(spectrum):
            candidate_game = rust_game.apply_chance_outcome(raw_json, outcome_index)
            candidate_snapshot = json.loads(candidate_game.json_snapshot())
            candidate_cards = candidate_snapshot["player_state"][actor_index]["dev_cards"]
            gained = [
                card for card in DEVELOPMENT_CARDS
                if int(candidate_cards[card]) - int(before_cards[card]) == 1
            ]
            deck_decreased = int(candidate_snapshot["development_deck_count"]) == before_deck_count - 1
            if len(gained) == 1 and deck_decreased:
                real_outcomes.append((outcome_index, float(entry["probability"]), gained[0]))
                materialized[outcome_index] = candidate_game
            else:
                phantom_outcomes.append(outcome_index)

        if not real_outcomes:
            raise RuntimeError(
                f"BUY_DEVELOPMENT_CARD spectrum has no real (card-drawing) outcomes: "
                f"spectrum={spectrum!r} before_cards={before_cards!r}"
            )

        weights = [prob for _, prob, _ in real_outcomes]
        selection = _weighted_choice(harness_rng, weights)
        outcome_index, _prob, card = real_outcomes[selection]
        new_rust_game = materialized[outcome_index]

        py_action = raw_action_to_python_action(raw_action, symbols)
        python_game.execute(
            py_action,
            action_record=symbols.ActionRecord(action=py_action, result=card),
        )
        return new_rust_game, ChanceOutcome(
            action_type, {"card": card, "phantom_outcomes": phantom_outcomes}
        )

    raise RuntimeError(f"apply_chance_step called with non-chance action_type={action_type!r}")


def _weighted_choice(rng: Any, weights: Sequence[float]) -> int:
    total = float(sum(weights))
    if total <= 0.0:
        raise RuntimeError(f"cannot sample from non-positive weights: {weights!r}")
    draw = rng.random() * total
    cumulative = 0.0
    for index, weight in enumerate(weights):
        cumulative += float(weight)
        if draw <= cumulative:
            return index
    return len(weights) - 1


def is_chance_action(raw_action: Sequence[Any]) -> bool:
    action_type = str(raw_action[1])
    if action_type in ("ROLL", "BUY_DEVELOPMENT_CARD"):
        return True
    if action_type == "MOVE_ROBBER":
        return raw_action[2][1] is not None
    return False


@dataclass(slots=True)
class GameResult:
    seed: int
    steps: int
    outcome: str  # "completed" | "step_limit" | "legal_action_mismatch" | "state_divergence" | "error"
    winner_rust: str | None = None
    winner_python: str | None = None
    detail: str = ""
    seated_colors: tuple[str, ...] = ()
    phantom_chance_outcomes: int = 0
    topic: str = "none"


def play_one_game(seed: int, config: EquivalenceConfig) -> GameResult:
    """Play a single game through both engines, forcing identical chance outcomes,
    diffing legal-action sets and state after every ply.

    Stops (and reports) at the first divergence found.
    """
    symbols = vendor_symbols()
    policy_rng = _random_module().Random(seed * 2 + 1)
    phantom_count = 0

    try:
        rust_game, python_game, seated_colors = build_paired_games(seed, config)
    except ActionMappingGap as error:
        return GameResult(seed=seed, steps=0, outcome="error", detail=f"setup failed: {error}")

    def _result(**kwargs: Any) -> GameResult:
        kwargs.setdefault("seated_colors", seated_colors)
        kwargs.setdefault("phantom_chance_outcomes", phantom_count)
        return GameResult(seed=seed, **kwargs)

    for step in range(int(config.max_steps)):
        winner_rust_color = rust_game.winning_color()
        winner_rust = str(winner_rust_color) if winner_rust_color is not None else None
        winner_python_color = python_game.winning_color()
        winner_python = winner_python_color.name if winner_python_color is not None else None
        if winner_rust is not None or winner_python is not None:
            if winner_rust != winner_python:
                return _result(
                    steps=step,
                    outcome="state_divergence",
                    topic="winner_mismatch_unclassified",
                    winner_rust=winner_rust,
                    winner_python=winner_python,
                    detail=f"winner mismatch at step {step}: rust={winner_rust!r} python={winner_python!r}",
                    seated_colors=seated_colors,
                )
            return _result(
                steps=step,
                outcome="completed",
                winner_rust=winner_rust,
                winner_python=winner_python,
                seated_colors=seated_colors,
            )

        try:
            ids, raw_actions = rust_legal_actions(rust_game, seated_colors, config.map_kind)
        except Exception as error:  # pragma: no cover - defensive, surfaced as a finding.
            return _result( steps=step, outcome="error",
                detail=f"failed to enumerate rust legal actions: {error}", seated_colors=seated_colors,
            )
        if not ids:
            return _result( steps=step, outcome="error",
                detail="rust engine reports zero legal actions with no winner", seated_colors=seated_colors,
            )

        only_rust, only_python = legal_action_diff(raw_actions, python_game.playable_actions)
        if only_rust or only_python:
            current_buildings = python_state_view(python_game, symbols)["buildings"]
            return _result(
                steps=step,
                outcome="legal_action_mismatch",
                topic=classify_legal_action_mismatch_topic(only_rust, only_python, current_buildings),
                detail=(
                    f"legal action set mismatch at step {step}: "
                    f"only_in_rust={sorted(only_rust)[:8]!r} only_in_python={sorted(only_python)[:8]!r}"
                ),
                seated_colors=seated_colors,
            )

        choice = policy_rng.randrange(len(ids))
        chosen_id, chosen_raw = ids[choice], raw_actions[choice]

        try:
            if is_chance_action(chosen_raw):
                rust_game, chance_outcome = apply_chance_step(
                    rust_game, python_game, chosen_raw, symbols=symbols, harness_rng=policy_rng
                )
                phantom_count += len(chance_outcome.detail.get("phantom_outcomes", ()))
            else:
                rust_game.execute_action_index(chosen_id, list(seated_colors), config.map_kind)
                py_action = raw_action_to_python_action(chosen_raw, symbols)
                python_game.execute(py_action)
        except ActionMappingGap as error:
            return _result( steps=step, outcome="error",
                detail=f"action mapping gap at step {step} for {chosen_raw!r}: {error}",
                seated_colors=seated_colors,
            )
        except Exception as error:
            return _result( steps=step, outcome="error",
                detail=f"exception applying {chosen_raw!r} at step {step}: {error!r}",
                seated_colors=seated_colors,
            )

        rust_view = rust_state_view(rust_game)
        python_view = python_state_view(python_game, symbols)
        mismatches = diff_state_views(rust_view, python_view)
        if mismatches:
            return _result(
                steps=step + 1,
                outcome="state_divergence",
                topic=classify_state_divergence_topic(rust_view, python_view, mismatches),
                detail=(
                    f"state mismatch after step {step} action={chosen_raw!r}: "
                    + "; ".join(mismatches[:8])
                ),
                seated_colors=seated_colors,
            )

    return _result(steps=int(config.max_steps), outcome="step_limit")


def _random_module() -> Any:
    import random as _random

    return _random


@dataclass(slots=True)
class SweepReport:
    num_games: int
    start_seed: int
    outcomes: dict[str, int] = field(default_factory=dict)
    topics: dict[str, int] = field(default_factory=dict)
    divergences: list[GameResult] = field(default_factory=list)
    completed_winners: dict[str, int] = field(default_factory=dict)
    total_steps: int = 0
    total_phantom_chance_outcomes: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "num_games": self.num_games,
            "start_seed": self.start_seed,
            "outcomes": self.outcomes,
            "topics": self.topics,
            "completed_winners": self.completed_winners,
            "total_steps": self.total_steps,
            "total_phantom_chance_outcomes": self.total_phantom_chance_outcomes,
            "divergences": [
                {
                    "seed": item.seed,
                    "steps": item.steps,
                    "outcome": item.outcome,
                    "topic": item.topic,
                    "winner_rust": item.winner_rust,
                    "winner_python": item.winner_python,
                    "detail": item.detail,
                    "seated_colors": list(item.seated_colors),
                }
                for item in self.divergences
            ],
        }


def run_sweep(
    num_games: int,
    start_seed: int,
    config: EquivalenceConfig,
    *,
    progress_every: int = 0,
) -> SweepReport:
    report = SweepReport(num_games=num_games, start_seed=start_seed)
    for offset in range(num_games):
        seed = start_seed + offset
        result = play_one_game(seed, config)
        report.outcomes[result.outcome] = report.outcomes.get(result.outcome, 0) + 1
        report.topics[result.topic] = report.topics.get(result.topic, 0) + 1
        report.total_steps += result.steps
        report.total_phantom_chance_outcomes += result.phantom_chance_outcomes
        if result.outcome == "completed" and result.winner_rust is not None:
            report.completed_winners[result.winner_rust] = (
                report.completed_winners.get(result.winner_rust, 0) + 1
            )
        if result.outcome in ("legal_action_mismatch", "state_divergence", "error"):
            report.divergences.append(result)
        if progress_every and (offset + 1) % progress_every == 0:
            print(
                f"[engine_equivalence] {offset + 1}/{num_games} games "
                f"({dict(report.outcomes)})",
                flush=True,
            )
    return report
