from __future__ import annotations

import json
from pathlib import Path

import pytest

from tools import a1_flywheel_turn as turn


def _write(path: Path, value: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")
    return path


def test_shared_teacher_lineage_rejects_stale_current_and_wrong_predecessor() -> None:
    def component(name: str, producer: str) -> dict:
        return {
            "component_id": name,
            "corpus_meta": {
                "a1_post_wave_audit": {
                    "source_provenance": {
                        "current": {"producer_checkpoint_sha256": producer}
                    }
                }
            },
        }

    parent = "sha256:" + "1" * 64
    predecessor = "sha256:" + "2" * 64
    descriptor = {
        "components": [
            component("n128", parent),
            component("n256", parent),
            component("predecessor_replay", predecessor),
        ]
    }
    value = turn.bind_teacher_lineage(
        descriptor,
        parent_checkpoint_sha256=parent,
        expected_predecessor_sha256=predecessor,
    )
    assert value["learner_parent_checkpoint_sha256"] == parent

    descriptor["components"][0] = component("n128", predecessor)
    with pytest.raises(turn.FlywheelTurnError, match="not generated by"):
        turn.bind_teacher_lineage(
            descriptor,
            parent_checkpoint_sha256=parent,
            expected_predecessor_sha256=predecessor,
        )


def _fixture(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    parent = _write(tmp_path / "parent.pt", "parent")
    handoff_file = _write(tmp_path / "handoff.json", "handoff")
    promotion_file = _write(tmp_path / "promotion.json", "promotion")
    campaign_file = _write(tmp_path / "campaign.json", "campaign")
    audit_file = _write(tmp_path / "audit.json", "audit")
    producer = turn._ref(parent, where="fixture producer")  # noqa: SLF001
    handoff = {
        "handoff_sha256": "sha256:" + "a" * 64,
        "promotion_receipt": {"transaction_id": "tx-2"},
        "registry_after": {"version": 2},
        "producer_identity": {
            "checkpoint": producer,
            "agent_identity_sha256": "sha256:" + "b" * 64,
            "search_config": {"n_full": 128},
        },
    }
    promotion = {"champion": {"sha256": "sha256:" + "c" * 64}}
    handoff_ref = turn._ref(handoff_file, where="fixture handoff")  # noqa: SLF001
    promotion_ref = turn._ref(promotion_file, where="fixture promotion")  # noqa: SLF001
    monkeypatch.setattr(
        turn,
        "verify_current_parent_handoff",
        lambda _path: (handoff, promotion, handoff_ref, promotion_ref),
    )
    campaign = {
        "schema_version": turn.POST_PROMOTION_CAMPAIGN_SCHEMA,
        "contract_sha256": "sha256:" + "d" * 64,
        "checkpoints": [{"role": "producer", **producer}],
    }
    campaign_ref = turn._ref(campaign_file, where="fixture campaign")  # noqa: SLF001
    monkeypatch.setattr(
        turn, "_campaign", lambda _path, _handoff: (campaign, campaign_ref)
    )
    audit = {
        "audit_sha256": "sha256:" + "e" * 64,
        "shard_inventory_sha256": "sha256:" + "f" * 64,
    }
    audit_ref = turn._ref(audit_file, where="fixture audit")  # noqa: SLF001
    monkeypatch.setattr(
        turn,
        "_audit",
        lambda _path, *, contract_sha256, producer_sha256: (audit, audit_ref),
    )
    data = tmp_path / "corpus"
    data.mkdir()
    meta = {
        "a1_post_wave_audit": {
            "file_sha256": audit_ref["sha256"],
            "audit_sha256": audit["audit_sha256"],
            "contract_sha256": campaign["contract_sha256"],
            "shard_inventory_sha256": audit["shard_inventory_sha256"],
        }
    }
    (data / "corpus_meta.json").write_text(json.dumps(meta), encoding="utf-8")
    verified = {
        "data_path": data,
        "producer": {"sha256": producer["sha256"]},
        "contract_sha256": "sha256:" + "8" * 64,
        "lock": {"source_campaign": campaign_ref},
        "payload_inventory_sha256": "sha256:" + "0" * 64,
        "selected_game_seed_set_sha256": "sha256:" + "1" * 64,
        "training_game_seed_set_sha256": "sha256:" + "2" * 64,
        "validation_game_seed_set_sha256": "sha256:" + "3" * 64,
        "corpus_row_count": 100,
        "training_row_count": 95,
        "validation_row_count": 5,
    }
    meta["a1_post_wave_audit"]["contract_sha256"] = verified["contract_sha256"]
    (data / "corpus_meta.json").write_text(json.dumps(meta), encoding="utf-8")
    kwargs = {
        "handoff_path": handoff_file,
        "campaign_path": campaign_file,
        "audit_path": audit_file,
        "verified": verified,
        "learner_parent": parent,
        "evaluation_parent": parent,
        "initializer": parent,
        "architecture_upgrade_receipt": None,
    }
    return kwargs


def test_turn_binds_exact_parent_and_rejects_stale_corpus_or_eval_parent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    kwargs = _fixture(tmp_path, monkeypatch)
    value = turn.build_turn(**kwargs)
    assert value["learner_parent"] == value["generator"]["checkpoint"]
    assert value["evaluation_parent"] == value["generator"]["checkpoint"]

    stale = dict(kwargs["verified"])
    stale["producer"] = {"sha256": "sha256:" + "9" * 64}
    with pytest.raises(turn.FlywheelTurnError, match="corpus contract producer"):
        turn.build_turn(**{**kwargs, "verified": stale})

    wrong = _write(tmp_path / "wrong.pt", "wrong")
    with pytest.raises(turn.FlywheelTurnError, match="evaluation parent"):
        turn.build_turn(**{**kwargs, "evaluation_parent": wrong})


def test_turn_rejects_corpus_to_audit_cross_binding(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    kwargs = _fixture(tmp_path, monkeypatch)
    meta_path = Path(kwargs["verified"]["data_path"]) / "corpus_meta.json"
    meta = json.loads(meta_path.read_text())
    meta["a1_post_wave_audit"]["audit_sha256"] = "sha256:" + "9" * 64
    meta_path.write_text(json.dumps(meta), encoding="utf-8")
    with pytest.raises(turn.FlywheelTurnError, match="does not bind"):
        turn.build_turn(**kwargs)


def test_turn_binds_production_composite_through_sealed_source_authority(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    kwargs = _fixture(tmp_path, monkeypatch)
    descriptor = _write(tmp_path / "production-composite.json", "{}")
    audit_ref = turn._ref(  # noqa: SLF001
        kwargs["audit_path"], where="fixture production audit"
    )
    verified = {
        **kwargs["verified"],
        "data_path": descriptor,
        "data_kind": "production_composite_v2",
        "source_authority": {
            "post_wave_audit": {
                "file_sha256": audit_ref["sha256"],
                "audit_sha256": "sha256:" + "e" * 64,
                "shard_inventory_sha256": "sha256:" + "f" * 64,
            }
        },
    }

    value = turn.build_turn(**{**kwargs, "verified": verified})

    assert value["corpus"]["meta"] == turn._ref(  # noqa: SLF001
        descriptor, where="fixture production descriptor"
    )

    tampered = {
        **verified,
        "source_authority": {
            "post_wave_audit": {
                **verified["source_authority"]["post_wave_audit"],
                "audit_sha256": "sha256:" + "9" * 64,
            }
        },
    }
    with pytest.raises(turn.FlywheelTurnError, match="does not bind"):
        turn.build_turn(**{**kwargs, "verified": tampered})
