#!/usr/bin/env python3
"""Immutable lineage binding for one non-bootstrap A1 flywheel turn.

This module contains no training policy.  It proves that a learner consumes a
fresh corpus generated by the champion promoted at the end of the immediately
preceding turn.  The proof is deliberately content addressed and replayable.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any, Mapping, Sequence


SCHEMA = "a1-flywheel-turn-v1"
CONSUMPTION_SCHEMA = "a1-flywheel-corpus-consumption-v1"
POST_PROMOTION_CAMPAIGN_SCHEMA = "a1-post-promotion-generation-campaign-v1"
AUDIT_SCHEMAS = {
    "a1-post-wave-audit-v2",
    "a1-post-wave-audit-v3",
    "a1-dual-arm-post-wave-audit-v1",
    "a1-dual-arm-derived-post-wave-audit-v1",
}
V16_COMBINED_ARCHITECTURE_PROFILE = (
    "a1-v1.6-public-card-count-meaningful-history-bias-free-v2"
)


class FlywheelTurnError(RuntimeError):
    """A stale, ambiguous, or non-replayable flywheel turn."""


def _digest(value: Any) -> str:
    raw = json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def _sha(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def _ref(path: Path, *, where: str) -> dict[str, str]:
    try:
        resolved = path.expanduser().resolve(strict=True)
    except OSError as error:
        raise FlywheelTurnError(f"cannot resolve {where}: {error}") from error
    if path.is_symlink() or not resolved.is_file():
        raise FlywheelTurnError(f"{where} must be a regular non-symlink file")
    return {"path": str(resolved), "sha256": _sha(resolved)}


def _load(path: Path, *, where: str) -> tuple[dict[str, Any], dict[str, str]]:
    reference = _ref(path, where=where)
    try:
        value = json.loads(Path(reference["path"]).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise FlywheelTurnError(f"cannot decode {where}: {error}") from error
    if not isinstance(value, dict):
        raise FlywheelTurnError(f"{where} must be a JSON object")
    return value, reference


def verify_current_parent_handoff(
    handoff_path: Path,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, str], dict[str, str]]:
    """Replay the committed promotion handoff and return its exact lineage.

    This is shared with ``a1_corrected_policy_arm``; there must be only one
    meaning of "current parent" in the learner stack.
    """

    from tools import a1_post_promotion_handoff as post

    handoff_path = handoff_path.expanduser().resolve(strict=True)
    handoff, handoff_ref = _load(handoff_path, where="post-promotion handoff")
    try:
        replayed = post.build_handoff(
            Path(str(handoff.get("promotion_receipt", {}).get("path", "")))
        )
    except post.HandoffError as error:
        raise FlywheelTurnError(
            f"post-promotion handoff replay failed: {error}"
        ) from error
    if handoff != replayed:
        raise FlywheelTurnError(
            "post-promotion handoff differs from committed live lineage"
        )
    receipt_path = Path(str(handoff["promotion_receipt"]["path"]))
    receipt, receipt_ref = _load(receipt_path, where="promotion receipt")
    if receipt_ref["sha256"] != handoff["promotion_receipt"]["sha256"]:
        raise FlywheelTurnError("promotion receipt bytes differ from handoff")
    dethroned = receipt.get("champion")
    if not isinstance(dethroned, Mapping) or not isinstance(
        dethroned.get("sha256"), str
    ):
        raise FlywheelTurnError(
            "promotion receipt does not bind the dethroned champion"
        )
    return handoff, receipt, handoff_ref, receipt_ref


def bind_teacher_lineage(
    descriptor_meta: Mapping[str, Any],
    *,
    parent_checkpoint_sha256: str,
    expected_predecessor_sha256: str | None = None,
) -> dict[str, Any]:
    """Bind current teacher components to parent and replay to predecessor."""

    rows: list[dict[str, str]] = []
    for component in descriptor_meta.get("components", ()):
        component_id = component.get("component_id")
        corpus_meta = component.get("corpus_meta")
        audit = (
            corpus_meta.get("a1_post_wave_audit")
            if isinstance(corpus_meta, Mapping)
            else None
        )
        provenance = (
            audit.get("source_provenance") if isinstance(audit, Mapping) else None
        )
        if not isinstance(provenance, Mapping) or not provenance:
            raise FlywheelTurnError(
                f"component {component_id} lacks producer provenance"
            )
        producer_shas = sorted(
            {
                row.get("producer_checkpoint_sha256")
                for row in provenance.values()
                if isinstance(row, Mapping)
                and isinstance(row.get("producer_checkpoint_sha256"), str)
            }
        )
        if len(producer_shas) != 1:
            raise FlywheelTurnError(
                f"component {component_id} has ambiguous producer lineage"
            )
        rows.append(
            {
                "component_id": str(component_id),
                "producer_checkpoint_sha256": producer_shas[0],
            }
        )
    if len(rows) < 2:
        raise FlywheelTurnError(
            "winning operator requires current data plus predecessor replay"
        )
    if any(
        row["producer_checkpoint_sha256"] != parent_checkpoint_sha256
        for row in rows[:-1]
    ):
        raise FlywheelTurnError(
            "current teacher data was not generated by the learner parent"
        )
    predecessor = rows[-1]["producer_checkpoint_sha256"]
    if predecessor == parent_checkpoint_sha256:
        raise FlywheelTurnError(
            "replay must come from the learner parent's predecessor"
        )
    if (
        expected_predecessor_sha256 is not None
        and predecessor != expected_predecessor_sha256
    ):
        raise FlywheelTurnError(
            "replay producer differs from the exact dethroned champion"
        )
    return {
        "schema_version": "a1-next-teacher-lineage-v1",
        "learner_parent_checkpoint_sha256": parent_checkpoint_sha256,
        "predecessor_checkpoint_sha256": predecessor,
        "expected_predecessor_checkpoint_sha256": expected_predecessor_sha256,
        "components": rows,
    }


def _campaign(
    path: Path, handoff: Mapping[str, Any]
) -> tuple[dict[str, Any], dict[str, str]]:
    from tools import a1_pre_wave_contract as campaign_tool

    path = path.expanduser().resolve(strict=True)
    try:
        value = campaign_tool.validate_generation_campaign(path, require_ready=True)
    except campaign_tool.ContractError as error:
        raise FlywheelTurnError(
            f"generation campaign replay failed: {error}"
        ) from error
    if value.get("schema_version") != POST_PROMOTION_CAMPAIGN_SCHEMA:
        raise FlywheelTurnError(
            "next turn requires a post-promotion generation campaign"
        )
    bound = value.get("promotion_handoff")
    if (
        not isinstance(bound, Mapping)
        or bound.get("handoff_sha256") != handoff.get("handoff_sha256")
        or bound.get("transaction_id")
        != handoff.get("promotion_receipt", {}).get("transaction_id")
    ):
        raise FlywheelTurnError("generation campaign binds a different promotion turn")
    return value, _ref(path, where="generation campaign")


def _audit(
    path: Path, *, contract_sha256: str, producer_sha256: str
) -> tuple[dict[str, Any], dict[str, str]]:
    value, reference = _load(path, where="completed generation audit")
    if value.get("schema_version") not in AUDIT_SCHEMAS:
        raise FlywheelTurnError("completed generation audit schema is not allowed")
    unhashed = dict(value)
    stated = unhashed.pop("audit_sha256", None)
    if stated != _digest(unhashed):
        raise FlywheelTurnError("completed generation audit semantic digest mismatch")
    if value.get("passed") is not True or value.get("errors") != []:
        raise FlywheelTurnError("generation audit is not a clean completed audit")
    if value.get("contract_sha256") != contract_sha256:
        raise FlywheelTurnError(
            "generation audit belongs to a different materialized lock"
        )
    shards = value.get("shards")
    if not isinstance(shards, list) or value.get("shard_inventory_sha256") != _digest(
        shards
    ):
        raise FlywheelTurnError("generation audit shard inventory drift")
    provenance = value.get("source_provenance")
    if not isinstance(provenance, Mapping) or not provenance:
        raise FlywheelTurnError("generation audit lacks producer provenance")
    observed = {
        row.get("producer_checkpoint_sha256")
        for row in provenance.values()
        if isinstance(row, Mapping)
    }
    if observed != {producer_sha256}:
        raise FlywheelTurnError(
            "generation audit was not produced by the promoted champion"
        )
    return value, reference


def build_turn(
    *,
    handoff_path: Path,
    campaign_path: Path,
    audit_path: Path,
    verified: Mapping[str, Any],
    learner_parent: Path,
    evaluation_parent: Path,
    initializer: Path,
    architecture_upgrade_receipt: Path | None = None,
) -> dict[str, Any]:
    """Build and replay one exact post-promotion learner-turn proof."""

    handoff, promotion, handoff_ref, promotion_ref = verify_current_parent_handoff(
        handoff_path
    )
    producer = handoff.get("producer_identity", {}).get("checkpoint")
    if not isinstance(producer, Mapping) or set(producer) != {"path", "sha256"}:
        raise FlywheelTurnError("handoff producer checkpoint is malformed")
    producer_sha = str(producer["sha256"])
    parent_ref = _ref(learner_parent, where="learner parent")
    evaluation_ref = _ref(evaluation_parent, where="evaluation parent")
    if parent_ref != producer or evaluation_ref != producer:
        raise FlywheelTurnError(
            "learner/evaluation parent differs from promoted producer"
        )
    if verified.get("producer", {}).get("sha256") != producer_sha:
        raise FlywheelTurnError(
            "corpus contract producer differs from promoted producer"
        )

    campaign, campaign_ref = _campaign(campaign_path, handoff)
    producers = [
        row for row in campaign.get("checkpoints", ()) if row.get("role") == "producer"
    ]
    if len(producers) != 1 or producers[0].get("sha256") != producer_sha:
        raise FlywheelTurnError("campaign producer differs from promoted producer")
    source_campaign = verified.get("lock", {}).get("source_campaign")
    if (
        not isinstance(source_campaign, Mapping)
        or dict(source_campaign) != campaign_ref
    ):
        raise FlywheelTurnError("corpus lock was not materialized from this campaign")
    audit, audit_ref = _audit(
        audit_path,
        contract_sha256=str(verified["contract_sha256"]),
        producer_sha256=producer_sha,
    )

    is_composite = verified.get("data_kind") == "production_composite_v2"
    if is_composite:
        meta_path = Path(str(verified["data_path"]))
        _descriptor, meta_ref = _load(meta_path, where="composite descriptor")
        authority = verified.get("source_authority")
        audit_binding = (
            authority.get("post_wave_audit")
            if isinstance(authority, Mapping)
            else None
        )
    else:
        meta_path = Path(str(verified["data_path"])) / "corpus_meta.json"
        meta, meta_ref = _load(meta_path, where="corpus metadata")
        audit_binding = meta.get("a1_post_wave_audit")
    if (
        not isinstance(audit_binding, Mapping)
        or audit_binding.get("file_sha256") != audit_ref["sha256"]
        or audit_binding.get("audit_sha256") != audit.get("audit_sha256")
        or (
            not is_composite
            and audit_binding.get("contract_sha256")
            != verified.get("contract_sha256")
        )
        or audit_binding.get("shard_inventory_sha256")
        != audit.get("shard_inventory_sha256")
    ):
        raise FlywheelTurnError("corpus metadata does not bind this generation audit")
    exact_corpus = {
        "meta": meta_ref,
        "contract_sha256": verified["contract_sha256"],
        "payload_inventory_sha256": verified["payload_inventory_sha256"],
        "selected_game_seed_set_sha256": verified["selected_game_seed_set_sha256"],
        "training_game_seed_set_sha256": verified["training_game_seed_set_sha256"],
        "validation_game_seed_set_sha256": verified["validation_game_seed_set_sha256"],
        "corpus_row_count": verified["corpus_row_count"],
        "training_row_count": verified["training_row_count"],
        "validation_row_count": verified["validation_row_count"],
    }

    initializer_ref = _ref(initializer, where="learner initializer")
    if architecture_upgrade_receipt is None:
        if initializer_ref != parent_ref:
            raise FlywheelTurnError(
                "non-upgrade initializer must be the exact learner parent"
            )
        initializer_binding: dict[str, Any] = {
            "mode": "exact_parent",
            "checkpoint": initializer_ref,
            "receipt": None,
        }
    else:
        from tools import a1_function_preserving_upgrade as upgrade

        try:
            replayed = upgrade.verify_receipt(architecture_upgrade_receipt)
        except upgrade.UpgradeError as error:
            raise FlywheelTurnError(
                f"architecture initializer receipt failed: {error}"
            ) from error
        if (
            replayed.get("source") != parent_ref
            or replayed.get("upgraded_initializer") != initializer_ref
        ):
            raise FlywheelTurnError(
                "architecture receipt does not connect parent to initializer"
            )
        initializer_binding = {
            "mode": "function_preserving_upgrade",
            "checkpoint": initializer_ref,
            "receipt": replayed["receipt"],
            "receipt_sha256": replayed["receipt_sha256"],
            "module": replayed["module"],
        }
        if replayed["module"] in {
            upgrade.MODULE_PUBLIC_CARD_COUNT_MEANINGFUL_HISTORY_V2,
            upgrade.MODULE_STRUCTURED_ACTION_VALUE_PUBLIC_CARD_COUNT_MEANINGFUL_HISTORY_V3,
        }:
            initializer_binding["architecture_profile"] = (
                V16_COMBINED_ARCHITECTURE_PROFILE
            )

    dethroned = promotion["champion"]["sha256"]
    value: dict[str, Any] = {
        "schema_version": SCHEMA,
        "promotion": {
            "handoff": handoff_ref,
            "handoff_sha256": handoff["handoff_sha256"],
            "receipt": promotion_ref,
            "transaction_id": handoff["promotion_receipt"]["transaction_id"],
            "dethroned_champion_sha256": dethroned,
        },
        "generator": {
            "checkpoint": dict(producer),
            "registry_version": handoff["registry_after"]["version"],
            "agent_identity_sha256": handoff["producer_identity"][
                "agent_identity_sha256"
            ],
            "search_config_sha256": _digest(
                handoff["producer_identity"]["search_config"]
            ),
        },
        "generation": {
            "campaign": campaign_ref,
            "campaign_contract_sha256": campaign["contract_sha256"],
            "materialized_lock_contract_sha256": verified["contract_sha256"],
            "audit": audit_ref,
            "audit_sha256": audit["audit_sha256"],
            "shard_inventory_sha256": audit["shard_inventory_sha256"],
            "selected_game_seed_set_sha256": verified["selected_game_seed_set_sha256"],
        },
        "corpus": exact_corpus,
        "learner_parent": parent_ref,
        "evaluation_parent": evaluation_ref,
        "initializer": initializer_binding,
    }
    value["turn_sha256"] = _digest(value)
    return value


def verify_turn(path: Path, *, verified: Mapping[str, Any]) -> dict[str, Any]:
    """Replay a turn file and its live immutable inputs."""

    value, _ = _load(path, where="flywheel turn")
    if value.get("schema_version") != SCHEMA:
        raise FlywheelTurnError("flywheel turn schema drift")
    unhashed = dict(value)
    stated = unhashed.pop("turn_sha256", None)
    if stated != _digest(unhashed):
        raise FlywheelTurnError("flywheel turn semantic digest mismatch")
    initializer = value.get("initializer", {})
    rebuilt = build_turn(
        handoff_path=Path(value["promotion"]["handoff"]["path"]),
        campaign_path=Path(value["generation"]["campaign"]["path"]),
        audit_path=Path(value["generation"]["audit"]["path"]),
        verified=verified,
        learner_parent=Path(value["learner_parent"]["path"]),
        evaluation_parent=Path(value["evaluation_parent"]["path"]),
        initializer=Path(initializer["checkpoint"]["path"]),
        architecture_upgrade_receipt=(
            None
            if initializer.get("receipt") is None
            else Path(initializer["receipt"]["path"])
        ),
    )
    if rebuilt != value:
        raise FlywheelTurnError("flywheel turn differs from replayed live lineage")
    return value


def write_turn(path: Path, value: Mapping[str, Any]) -> None:
    path = path.expanduser().resolve(strict=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(dict(value), indent=2, sort_keys=True).encode("utf-8") + b"\n"
    try:
        descriptor = os.open(
            path,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0),
            0o444,
        )
    except FileExistsError as error:
        raise FlywheelTurnError(
            f"flywheel turn output must be fresh: {path}"
        ) from error
    with os.fdopen(descriptor, "wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())


def main(argv: Sequence[str] | None = None) -> int:
    raise SystemExit("use tools/a1_iteration_orchestrator.py initialize-next")


if __name__ == "__main__":
    main()
